<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\crypto\src\BouncyCastle.Crypto.csproj" />
    <ProjectReference Include="..\DtlsImpl\DtlsImpl.csproj" />
  </ItemGroup>

</Project>
